const ShopActionTypes = {
  FETCH_COLLECTION_START: "FETCH_COLLECTION_START",
  FETCH_COLLECTION_SUCCEED: "FETCH_COLLECTION_SUCCEED",
  FETCH_COLLECTION_FAILED: "FETCH_COLLECTION_FAILED",
};

export default ShopActionTypes;
